### ISSUE TITLE
☂️ graphql-server v3

### ISSUE THREAD

**Issue by jkimbo** [graphql-python/graphql-server#44]
Issue to track v3 release:

# TODO

* [x] Upgrade to graphql-core v3
* [x] Merge separate server integration packages into repo (#34 )
* [x] Rename package and github repo to `graphql-server`
* [x] Add notices to framework specific libraries that they are deprecated and that people should use the graphql-server library
* [x] Add documentation to README about how to integrate with different frameworks
* [x] Support latest versions of frameworks (currently some are restricted to older versions):
  - [x] Flask 2
  - [x] Sanic 21
  - [x] Quart 0.16

**Comment by geyang** [comment]
Just want to bump this up, Sanic is already up to `22.9.0`. This is currently stuck at `20.9.0`.

**Comment by syrusakbary** [comment]
Flask, Sanic and Quart are now fully supported as well as other frameworks.

Code is updated `main`, it will be also soon released in PyPI as `3.0.0b8`
